* commands

`npm start`

`npm run deploy`
* TODOs
- refresh all button. random button. swipe right to full screen mode. swipe left to freeze. have fixed height.
- timer with bell: random log scale time
- can I use text to speech to read out things? eg. emotions, numbers
- make font size adjust automatically
** generators
- archetypes: ghost, cowboy, pirate,  adventurer, detective, knight, superhero, evil henchman, supervillain, sidekick, cheerleader, jock, helicopter parent, pushover parent, entitled nerd, doctor, teacher, butler
- body parts: nose, fingers, toes, hips, chair
- voice: batman, old person, small and squeak-y, nasal nerd, child, robot, pirate, southern, stutter, whisper, yelling, repeat the last thing said, leprechaun,
- small objects: yoyo, eating cake, eating pizza, eating a sandwich, texting on phone, typing on computer, Rubik's cube, drinking tea, smoking a cigarette, drinking beer, drinking wine, eating nachos, playing with a fidget spinner, reading a book, talking notes, briefcase, hand grips, petting cat
- situations: walking a dog, cleaning dishes, brushing teeth, putting make up, trying clothes, chopping wood, gardening, cleaning the house, cooking, watching tv, working on the computer,
