const props = [
  "Soccer Ball",
  "Basketball",
  "Yoyo",
  "Tea",
  "Beer"
];

const secretWants = [
  "Validation",
  "A Hug",
  "Power",
  "Efficiency",
  "To Be Left Alone",
  "A Surprise",
  "To Be Feared",
  "To Be The One",
  "Romance",
  "Legacy",
  "The Newest Thing",
  "A Gift",
  "Acts Of Service",
  "Make A Deal",
  "To Have Someone Else Do Your Job",
  "Be Taught How To Read",
  "Be Seen As Smart",
  "Your Soul",
  "To Be Serenaded",
  "Be Seen As Funny",
  "Apology",
  "Forgiveness",
  "A Sandwich",
  "To Hint At Secrets But Not Reveal Them",
  "To Be Seen As Cool",
  "To Be Like Partner",
  "To Be Admired",
  "To Learn",
  "Adventure",
  "Safety",
  "Fame",
  "The Right Answer",
  "A Massage",
  "Give A Massage",
];

const animals = [
  "Meerkat",
  "Peacock",
  "Owl",
  "Lion",
  "Dog",
  "Cat",
  "Parrot",
  "Snake",
  "Mouse",
  "Raccoon",
  "Sloth",
  "Lizard",
  "Bear",
  "Rabbit",
  "Chicken",
  "Crab",
  "Snail",
  "Praying Mantis",
  "Frog",
];

const characterQuestions = [
  "What's your name?",
  "What's in your front right pocket?",
  "How old are you?",
  "What colour is your bedroom?",
  "What do you do for a job?",
  "What's your deepest secret?",
  "Where do you live?",
  "What scares you?",
  "What animal was your first pet (and what was it called?)",
  "Who's your closest friend (and how did you meet)?",
  "Where did you go to school (and did you enjoy it)?",
  "Where did you last go on holiday (and what was your opinion of it)?",
  "What's your favourite food?",
  "What's your favourite song?",
];

export default {
  props,
  secretWants,
  animals,
  characterQuestions,
};
